name: auto-labeler

on: workflow_dispatch
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  auto-labeler:
    uses: gofiber/.github/.github/workflows/auto-labeler.yml@main
    secrets:
      github-token: ${{ secrets.ISSUE_PR_TOKEN }}
    with:
      config-path: .github/labeler.yml
      config-repository: gofiber/fiber
