name: Dependabot On-Demand

on: workflow_dispatch
permissions:
  contents: write

jobs:
  trigger:
    uses: gofiber/.github/.github/workflows/dependabot-on-demand.yml@main
    secrets:
      push-token: ${{ secrets.PR_TOKEN }}
